clear all;
P0 = 100;
L = 2*P0 + 1;
overlap = 1.25*P0 + 1;
window = hanning(L, 'symmetric');
seg1 = [window; zeros(2*overlap, 1)];
seg2 = [zeros(overlap, 1); window; zeros(overlap, 1)];
seg3 = [zeros(2*overlap, 1); window];

plot(seg1, 'DisplayName', 'Window 1');
hold on;
plot(seg2, 'DisplayName', 'Window 2');
plot(seg3, 'DisplayName', 'Window 3');
plot(seg1 + seg2 + seg3, 'DisplayName', 'Sum of windows');
ylim([0 1.1]);
hold off;
legend('location', 'southeast');
ylabel("Amplitude");
xlabel("Samples");
title("Windows spaced greater than P0");